### ISSUE TITLE
Clarify which version of black is required for formatting

### ISSUE THREAD

**Issue by sebastien-rosset** [ansible-collections/ansible.utils#139]
##### SUMMARY

The README.md file (https://github.com/ansible-collections/ansible.utils/blame/main/README.md#L140) states:

> Use of the latest version of black is required for formatting (black -l79)

However:
1. As of 2/6/2022, the latest version of black is 22.1.0. The CI uses `black` an older version 19.3b0.
2. Even though `black` does have stability guarantees, some changes are expected across versions. Here is the black stability policy: https://black.readthedocs.io/en/latest/the_black_code_style/index.html#stability-policy
3.  The local formatting by `black -l79` in a local workspace does not match the formatting by `black` in the zuul CI.

It might be useful to run the zuul CI with the `--diff` option instead of the `--check` option. That would make it easier to identify formatting differences between CI and local workspace.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

black (python formatting)

##### ANSIBLE VERSION

```paste below

```

##### ADDITIONAL INFORMATION

When the `ansible-tox-linters` job runs in CI, the following output may be generated. However, we can't tell what would change. This makes it challenging to identify specific differences between `black` running in CI vs local workspace.
 
```console
would reformat /home/zuul/src/github.com/ansible-collections/ansible.utils/tests/unit/plugins/filter/test_ipsubnet.py
would reformat /home/zuul/src/github.com/ansible-collections/ansible.utils/tests/unit/plugins/sub_plugins/validate/test_config.py
All done! 💥 💔 💥
2 files would be reformatted, 163 files would be left unchanged.
ERROR: InvocationError for command /home/zuul/src/github.com/ansible-collections/ansible.utils/.tox/linters/bin/black -v -l79 --check . (exited with code 1)
```

I'm trying to figure out if the issue is caused by the version of black or by configuration. The formatting diffs are for function documentation. Example:
https://github.com/ansible-collections/ansible.utils/pull/131/files#diff-21f3ea4214265402c6b1447e96218830431ff1090545d358a4df63d425e095acL692
```diff
-    """ Check if string is a HW/MAC address and filter it """
+    """Check if string is a HW/MAC address and filter it"""
```

**Comment by sebastien-rosset** [comment]
From the `black` code styles https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html:

> Black also processes docstrings. Firstly the indentation of docstrings is corrected for both quotations and the text within, although relative indentation in the text is preserved. Superfluous trailing whitespace on each line and unnecessary new lines at the end of the docstring are removed. All leading tabs are converted to spaces, but tabs inside text are preserved. Whitespace leading and trailing one-line docstrings is removed.

**Comment by cidrblock** [comment]
@sebastien-rosset Sorry, we fell behind a bit on the version, it's updated and defined in the precommit config now, which should help keep it updated: https://github.com/ansible-collections/ansible.utils/blob/main/.pre-commit-config.yaml#L17

**Comment by sebastien-rosset** [comment]
Thank you!
