### ISSUE TITLE
Moving ipaddr from ansible.netcommon to ansible.utils breaks stuff

### ISSUE THREAD

**Issue by sebastianw** [ansible-collections/ansible.utils#148]
##### SUMMARY
When the `ipaddr` filter moved from `ansible.netcommon` to `ansible.utils` it changed behaviour and breaks downstream usage.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ipaddr

For more information see https://github.com/ansible-collections/ansible.netcommon/issues/375

**Comment by ashwini-mhatre** [comment]
We have released utils 2.5.2 and netcommon 2.6.1 which fixed https://github.com/ansible-collections/ansible.netcommon/issues/375 and https://github.com/ansible-collections/ansible.utils/issues/148 issues.

For FQDN issue ansible-core team already merged https://github.com/ansible/ansible/pull/77210. This fix will be available in 28th march release.

which means,
For non fqdn ipaddr filters users can use old netcommon collection version 2.5.1 as workaround until core-team will release ansible code(28th march). For fqdn ipaddr filters users can use latest versions of any of netcommon(2.6.1) or utils(2.5.2) cc: @trishnaguha
