### ISSUE TITLE
ipaddr('prefix') returns [prefix] instead of just prefix

### ISSUE THREAD

**Issue by SRv6d** [ansible-collections/ansible.utils#151]
##### SUMMARY
ipaddr('prefix') returns `[prefix]` instead of just `prefix` like ansible.netcommon.ipaddr did before the migration.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ipaddr('prefix')

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.3]
  python version = 3.9.10 (main, Jan 15 2022, 11:40:53) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below

# /Users/.../ansible/.venv-ansible/lib/python3.9/site-packages/ansible_collections
Collection    Version
------------- -------
ansible.utils 2.5.0

# /Users/.../.ansible/collections/ansible_collections
Collection    Version
------------- -------
ansible.utils 2.5.1
```

##### CONFIGURATION

```paste below
DEFAULT_STDOUT_CALLBACK(/Users/.../ansible/ansible.cfg) = yaml
```

##### STEPS TO REPRODUCE

```yaml
- set_fact:
     ansible_default_ipv4:
       address: "10.10.184.252"
       netmask: "255.255.240.0"

- debug:
    msg: "{{ (ansible_default_ipv4.address + '/' + ansible_default_ipv4.netmask) | ansible.netcommon.ipaddr('prefix') }}"
```

##### EXPECTED RESULTS

Result of debug: `20`

##### ACTUAL RESULTS

Result of debug: `[20]`

**Comment by AdamMack2007** [comment]
@SRv6d This has been fixed in version 2.5.2 released a few hours ago, issue and Merge Requests can be found [here](https://github.com/ansible-collections/ansible.utils/issues/148)

I had issues similar to this with the "address" filter returning a list as opposed to a string and can confirm that 2.5.2 fixed both issues.

**Comment by SRv6d** [comment]
@AdamMack2007 That's great to know, although ansible-galaxy isn't picking it up for me. I didn't specify a version for `ansible.utils` in me `requirements.yml`, but ansible uses

**Comment by SRv6d** [comment]
Thanks, the latest release does fix it. Closing the issue.
