### ISSUE TITLE
Undo DOCUMENTATION changes made in #172

### ISSUE THREAD

**Issue by cidrblock** [ansible-collections/ansible.utils#178]
##### SUMMARY

In both the devel and milestone branches for ansible-core 2.14, a regression was introduced which causes ansible test sanity to fail if the constant `DOCUMENTATION` is used anywhere, more than once, in a lookup plugin.

A workaround was put in place to get it from globals lowercased.

When the below ansible-core issue is fixed, these changes need to be removed.

This is what was done in each of the ansible.utils lookup plugins.
```
schema = [v for k, v in globals() if k.lower() == "documentation"]
```

The is the ansible-core issue that needs to be resolved prior to removing the code from the ansible.utils lookup plugins:
 https://github.com/ansible/ansible/issues/77764

This is the PR where the lookup plugin changes went in:
Related #172 

##### ISSUE TYPE
- Cleanup

##### COMPONENT NAME

lookup plugins

**Comment by ashwini-mhatre** [comment]
PR merged
