### ISSUE TITLE
textfsm 1.1.3 is broken

### ISSUE THREAD

**Issue by ColonelBundy** [ansible-collections/ansible.utils#193]
##### SUMMARY
Due to the nature of this module not using strict versioning in [requirements.txt](https://github.com/ansible-collections/ansible.utils/blob/main/requirements.txt) which is very bad practice due to issues like this. In short and as the title says, textfsm 1.1.3 has issues and cannot be installed which breaks anything that is using ansible.utils.

##### ISSUE TYPE
- Bug Report

issue in the textfsm repo https://github.com/google/textfsm/issues/105

**Comment by Akasurde** [comment]
resolved_by_pr #194

**Comment by Akasurde** [comment]
As far as I can tell, this issue was solved on July 13 (https://github.com/google/textfsm/issues/105#issuecomment-1182889708) so I'm closing this. Feel free to reopen if you disagree.
