### ISSUE TITLE
Fix documentation errors for plugin documentation

### ISSUE THREAD

**Issue by samccann** [ansible-collections/ansible.utils#214]
##### SUMMARY

ansible.utils shows errors on docs.ansible.com that prevent the plugin documentation from displaying for users.

##### ISSUE TYPE
- Documentation Report

##### ANSIBLE VERSION

```paste below
2.14
```

**Comment by samccann** [comment]
Errors are:
ansible.utils.index_of filter - 1 validation error for PositionalDocSchema
doc -> options -> value -> description -> 1
  str type expected (type=type_error.str)

ansible.utils.ipaddr filter - 1 validation error for PositionalDocSchema
doc -> options -> query -> description -> 2
  str type expected (type=type_error.str)

ansible.utils.usable_range filter - 1 validation error for PositionalDocSchema
doc -> options -> ip -> description -> 1
  str type expected (type=type_error.str)

**Comment by samccann** [comment]
All test plugin documentation is also reporting errors on the docsite. Click the links below to see the errors reported:

[in_any_network test](https://docs.ansible.com/ansible/devel/collections/ansible/utils/in_any_network_test.html#ansible-collections-ansible-utils-in-any-network-test) –

[in_network test](https://docs.ansible.com/ansible/devel/collections/ansible/utils/in_network_test.html#ansible-collections-ansible-utils-in-network-test) –

[in_one_network test](https://docs.ansible.com/ansible/devel/collections/ansible/utils/in_one_network_test.html#ansible-collections-ansible-utils-in-one-network-test) –

[ip test](https://docs.ansible.com/ansible/devel/collections/ansible/utils/ip_test.html#ansible-collections-ansible-utils-ip-test) –

[ip_address test](https://docs.ansible.com/ansible/devel/collections/ansible/utils/ip_address_test.html#ansible-collections-ansible-utils-ip-address-test) –

[ipv4 test](https://docs.ansible.com/ansible/devel/collections/ansible/utils/ipv4_test.html#ansible-collections-ansible-utils-ipv4-test) –

[ipv4_address test](https://docs.ansible.com/ansible/devel/collections/ansible/utils/ipv4_address_test.html#ansible-collections-ansible-utils-ipv4-address-test) –

[ipv4_hostmask test](https://docs.ansible.com/ansible/devel/collections/ansible/utils/ipv4_hostmask_test.html#ansible-collections-ansible-utils-ipv4-hostmask-test) –

[ipv4_netmask test](https://docs.ansible.com/ansible/devel/collections/ansible/utils/ipv4_netmask_test.html#ansible-collections-ansible-utils-ipv4-netmask-test) –

[ipv6 test](https://docs.ansible.com/ansible/devel/collections/ansible/utils/ipv6_test.html#ansible-collections-ansible-utils-ipv6-test) –

[ipv6_address test](https://docs.ansible.com/ansible/devel/collections/ansible/utils/ipv6_address_test.html#ansible-collections-ansible-utils-ipv6-address-test) –

[ipv6_ipv4_mapped test](https://docs.ansible.com/ansible/devel/collections/ansible/utils/ipv6_ipv4_mapped_test.html#ansible-collections-ansible-utils-ipv6-ipv4-mapped-test) –

[ipv6_sixtofour test](https://docs.ansible.com/ansible/devel/collections/ansible/utils/ipv6_sixtofour_test.html#ansible-collections-ansible-utils-ipv6-sixtofour-test) –

[ipv6_teredo test](https://docs.ansible.com/ansible/devel/collections/ansible/utils/ipv6_teredo_test.html#ansible-collections-ansible-utils-ipv6-teredo-test) –

[loopback test](https://docs.ansible.com/ansible/devel/collections/ansible/utils/loopback_test.html#ansible-collections-ansible-utils-loopback-test) –

[mac test](https://docs.ansible.com/ansible/devel/collections/ansible/utils/mac_test.html#ansible-collections-ansible-utils-mac-test) –

[multicast test](https://docs.ansible.com/ansible/devel/collections/ansible/utils/multicast_test.html#ansible-collections-ansible-utils-multicast-test) –

[private test](https://docs.ansible.com/ansible/devel/collections/ansible/utils/private_test.html#ansible-collections-ansible-utils-private-test) –

[public test](https://docs.ansible.com/ansible/devel/collections/ansible/utils/public_test.html#ansible-collections-ansible-utils-public-test) –

[reserved test](https://docs.ansible.com/ansible/devel/collections/ansible/utils/reserved_test.html#ansible-collections-ansible-utils-reserved-test) –

[resolvable test](https://docs.ansible.com/ansible/devel/collections/ansible/utils/resolvable_test.html#ansible-collections-ansible-utils-resolvable-test) –

[subnet_of test](https://docs.ansible.com/ansible/devel/collections/ansible/utils/subnet_of_test.html#ansible-collections-ansible-utils-subnet-of-test) –

[supernet_of test](https://docs.ansible.com/ansible/devel/collections/ansible/utils/supernet_of_test.html#ansible-collections-ansible-utils-supernet-of-test) –

[unspecified test](https://docs.ansible.com/ansible/devel/collections/ansible/utils/unspecified_test.html#ansible-collections-ansible-utils-unspecified-test) –

**Comment by samccann** [comment]
Related to https://github.com/ansible-community/community-team/issues/65

**Comment by felixfontein** [comment]
Fixed by #215.
