### ISSUE TITLE
Please tag your releases

### ISSUE THREAD

**Issue by mariolenz** [ansible-collections/ansible.utils#241]
##### SUMMARY

It looks like you are actively working on this collection and release new versions on galaxy. However, you don't tag them in this repository, which is a [requirement for collections that are part of the community package](https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst#repository-management).

Please tag your release, otherwise we will consider removing `ansible.utils` from [ansible](https://pypi.org/project/ansible/).

Not ot put too fine a point on it, but it looks like an easy thing to fix where we don't have to discuss much ;-)

##### ISSUE TYPE
- Bug Report

**Comment by mariolenz** [comment]
Sorry, it looks like [you do](https://github.com/ansible-collections/ansible.utils/tags). My failure :-/

**Comment by felixfontein** [comment]
The confusing part is that GH releases (https://github.com/ansible-collections/ansible.utils/releases) have been created for the first few releases, but not anymore since then - so GitHub says the latest release is 2.0.1 from March 2021, while there have been multiple newer releases.
