### ISSUE TITLE
:warning:  Testing with python3.8 fails

### ISSUE THREAD

**Issue by cidrblock** [ansible-collections/ansible.utils#249]
On 31 Mar 2023, ansible-navigator 3.0.0 was released which dropped support for python 3.8.

This impacts the integration testing matrix that currently includes ansible 2.9 and python 3.8.

An additional workflow was added to work around this issue until such time the decision is made to change the main workflow.

https://github.com/ansible-network/github_actions/blob/main/.github/workflows/integration_simple_39.yml

The above workflow can be used as a workaround but does not run integration tests with ansible 2.9 or python 3.8 which may or may not be required.

**Comment by Qalthos** [comment]
Is this still necessary now that 3.0.2 is out?

**Comment by cidrblock** [comment]
nope :) thx
