### ISSUE TITLE
No changelog since 2.9.0

### ISSUE THREAD

**Issue by felixfontein** [ansible-collections/ansible.utils#268]
##### SUMMARY
The last changelog entry for this collection is for 2.9.0 in https://github.com/ansible-collections/ansible.utils/blob/main/changelogs/changelog.yaml. For all 2.10.x releases there is none.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
changelog

**Comment by KB-perByte** [comment]
Hey @felixfontein we made a release 2.10.2, which has the updated changelog. 
Due to some manual changes because of CI updates, the entry in changelog.yml was reverted.
let me know if it is fine, or we shall push a new release as things are stable.
Regards

**Comment by felixfontein** [comment]
@KB-perByte the current release doesn't contain the entries in changelogs/changelog.yaml, so it's better to push a new release (2.10.3).

BTW, what happened to 2.10.0 and 2.10.1? They are also not tagged in this repository (which violates the Ansible inclusion requirements: https://docs.ansible.com/ansible/devel/community/collection_contributors/collection_requirements.html#repository-management).

**Comment by KB-perByte** [comment]
@felixfontein I'll try to push a 2.10.3 release soon! I'll keep you updated.

**Comment by KB-perByte** [comment]
A release for 2.10.3 is made and a changelog has been added for the missing releases.
Regards.

**Comment by felixfontein** [comment]
@KB-perByte thanks a lot!
