### ISSUE TITLE
fact_diff show all common lines

### ISSUE THREAD

**Issue by ryanmerolle** [ansible-collections/ansible.utils#311]
##### SUMMARY
Set a fact_diff argument to show all common lines instead of only showing three lines above and below a diff.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
fact_diff

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by ashwini-mhatre** [comment]
Fixed: https://github.com/ansible-collections/ansible.utils/pull/323
