### ISSUE TITLE
Add xml_to_json and json_to_xml filter plugins

### ISSUE THREAD

**Issue by ganeshrn** [ansible-collections/ansible.utils#53]
##### SUMMARY

Add `xml_to_json` filter plugin to convert a `xml` string to `json` structure using `xmltodict` as default parsing engine.
```
{{ some_xml_string_variable | xml_to_json(engine='xmltodict') }}
```

Add `json_to_xml` filter plugin to convert a `json` string to `xml` structure using `xmltodict` as default parsing engine.
```
{{ some_json_string_variable | json_to_xml(engine='xmltodict') }}
```
##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by ashwini-mhatre** [comment]
https://github.com/ansible-collections/ansible.utils/pull/56 fixes this
