### ISSUE TITLE
fact_diff filter or lookup

### ISSUE THREAD

**Issue by ryanmerolle** [ansible-collections/ansible.utils#78]
##### SUMMARY
The fact_diff module is great for comparing facts, but I often use the asset module  to compare vars.  It would be useful to be able to use a fact_diff type function in a fail message of an assert task.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
fact_diff

**Comment by cigamit** [comment]
Yes, I second this.  It would nice to have a "fact_diff" lookup plugin.

My use case is that I am building reports of changes in Ansible based upon the results of another previous job template run in Controller.  The "Show Changes" mode in Controller will display the changes in a diff like format, but getting the same data from the API for my report returns the full contents of the files/changes.  So I want to pass the 2 variables (and 2 file headers) through a lookup plugin to convert it to a diff format for easier viewing.

I may take a swing at hacking something together using the code from the action plugin.

**Comment by NilashishC** [comment]
I'm not sure I understand how fact_diff would fit in as a lookup plugin. But I totally understand the use case of it as a filter plugin, used in the `fail_msg` of an assert task.

@cigamit If you can share a sample play with your lookup plugin idea, we can explore implementing it.

**Comment by cigamit** [comment]
@NilashishC 
Here is the plugin I roughly hacked together
https://github.com/cigamit/ansible_misc/blob/master/change_audit/lookup_plugins/diff.py
and here is a template where I use it
https://github.com/cigamit/ansible_misc/blob/master/change_audit/templates/changes.html.j2

**Comment by ashwini-mhatre** [comment]
@ryanmerolle I start working on this

**Comment by ryanmerolle** [comment]
Thanks!
